# This is a dummy file intended just to dump
# all project parameters got from app.ini
# -----------------------------------------------
#           PACKAGE: ${PACKAGE}
#       APPLICATION: ${APPLICATION}
#       ENVIRONMENT: ${ENVIRONMENT}
#      DOCKER_IMAGE: ${DOCKER_IMAGE}
#  APP_BACKEND_PORT: ${APP_BACKEND_PORT}
#  APP_ENDPOINT_URL: ${APP_ENDPOINT_URL}
# APP_ENDPOINT_PATH: ${APP_ENDPOINT_PATH}
