#           CLUSTER: ${CLUSTER}
#         NAMESPACE: ${NAMESPACE}
#       APPLICATION: ${APPLICATION}
#   CONTAINER_IMAGE: ${CONTAINER_IMAGE}
#    CONTAINER_PORT: ${CONTAINER_PORT}
#   APPLICATION_URL: ${APPLICATION_URL}
#  APPLICATION_PATH: ${APPLICATION_PATH}
