---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${APPLICATION}
  namespace: ${NAMESPACE}
  labels:
    app: ${APPLICATION}
    env: ${CLUSTER}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION}
      env: ${CLUSTER}
  template:
    metadata:
      labels:
        app: ${APPLICATION}
        env: ${CLUSTER}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1234"
    spec:
      containers:
      - name: ${APPLICATION}-container
        image: ${CONTAINER_IMAGE}
        ports:
        - containerPort: ${CONTAINER_PORT}
        env:
        - name: CLUSTER
          value: ${CLUSTER}
        - name: APPLICATION
          value: ${APPLICATION}
        envFrom:
        - configMapRef:
            name: ${APPLICATION}-config

---
kind: Service
apiVersion: v1
metadata:
  name: ${APPLICATION}-service
  namespace: ${NAMESPACE}
  labels:
    app: ${APPLICATION}
    env: ${CLUSTER}
spec:
  selector:
     app: ${APPLICATION}
     env: ${CLUSTER}
  ports:
    - name: http
      port: ${CONTAINER_PORT}

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ${APPLICATION}-ingress
  namespace: ${NAMESPACE}
  labels:
    app: ${APPLICATION}
    env: ${CLUSTER}
  annotations:
    nginx.ingress.kubernetes.io/app-root: ${APPLICATION_PATH}
spec:
  tls:
  - hosts:
    - ${APPLICATION_URL}
  rules:
  - host: ${APPLICATION_URL}
    http:
      paths:
      - path: ${APPLICATION_PATH}
        backend:
          serviceName: ${APPLICATION}-service
          servicePort: ${CONTAINER_PORT}

